# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quorapp', '0002_auto_20160524_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='isspam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
