# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quorapp', '0004_auto_20160526_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagepath',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
