# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quorapp', '0005_auto_20160526_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 5, 26, 17, 43, 44, 123888, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 5, 26, 17, 43, 44, 124396, tzinfo=utc), null=True),
        ),
    ]
