# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quorapp', '0012_auto_20160527_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 5, 30, 8, 56, 3, 531031, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 5, 30, 8, 56, 3, 531304, tzinfo=utc), null=True),
        ),
    ]
