# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 08:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quorapp', '0013_auto_20160530_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 5, 30, 8, 57, 58, 155160, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 5, 30, 8, 57, 58, 155384, tzinfo=utc), null=True),
        ),
    ]
