# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 07:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quorapp', '0018_auto_20160604_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowers',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='userfollowers',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 8, 7, 15, 58, 991648, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 8, 7, 15, 58, 991942, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='usertopics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserFollowers',
        ),
    ]
